export const userData = [
  {
    id: "1",
    image:
      "https://images.pexels.com/photos/4171757/pexels-photo-4171757.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Jane Smith",
    studentId: "34rt56",
    referralCode: "905utw",
    gender: "f",
    status: "active",
    date: "12/4/2023",
    email: "jsmith@test.com",
  },
  {
    id: "2",
    image:
      "https://media.istockphoto.com/id/1299077582/photo/positivity-puts-you-in-a-position-of-power.jpg?b=1&s=612x612&w=0&k=20&c=izi-YNE62pUFbtRuN90WD32P-NNnLKIq9YC-dwKHDTw=",
    name: "Clara Amaechi",
    studentId: "5je503",
    referralCode: "03pdc2",
    gender: "f",
    status: "active",
    date: "1/3/2023",
    email: "camaechi@test.com",
  },
  {
    id: "3",
    image:
      "https://media.istockphoto.com/id/1201144328/photo/smiling-black-man-in-suit-posing-on-studio-background.jpg?b=1&s=612x612&w=0&k=20&c=ybH24-eZo01LmM6NvB2oMYkwmTn-8DSqbF_y3zZRGSU=",
    name: "Tambuwal Jamal",
    studentId: "p23y5t",
    referralCode: "e5te45",
    gender: "m",
    status: "pending",
    date: "16/8/2023",
    email: "tjamal@test.com",
  },
  {
    id: "4",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGCpkvpG7QbE4yZPONQK2jSt8rTm2GKIvwvQ&usqp=CAU",
    name: "Steven Ogunbiyi",
    studentId: "j3t0p2",
    referralCode: "p2sc67",
    gender: "m",
    status: "pending",
    date: "3/9/2023",
    email: "sogunbiyi@test.com",
  },
  {
    id: "5",
    image:
      "https://media.istockphoto.com/id/1201144328/photo/smiling-black-man-in-suit-posing-on-studio-background.jpg?b=1&s=612x612&w=0&k=20&c=ybH24-eZo01LmM6NvB2oMYkwmTn-8DSqbF_y3zZRGSU=",
    name: "Shade Taylor",
    studentId: "6u8bo9",
    referralCode: "pa2byr",
    gender: "f",
    status: "pending",
    date: "17/8/2023",
    email: "staylor@test.com",
  },
  {
    id: "6",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGCpkvpG7QbE4yZPONQK2jSt8rTm2GKIvwvQ&usqp=CAU",
    name: "Joseph Alade",
    studentId: "e2vtm8",
    referralCode: "76d5ty",
    gender: "m",
    status: "active",
    date: "19/11/2023",
    email: "jalade@test.com",
  },
  {
    id: "7",
    image:
      "https://media.istockphoto.com/id/1299077582/photo/positivity-puts-you-in-a-position-of-power.jpg?b=1&s=612x612&w=0&k=20&c=izi-YNE62pUFbtRuN90WD32P-NNnLKIq9YC-dwKHDTw=",
    name: "Vera Salome",
    studentId: "9rt43s",
    referralCode: "e5te37",
    gender: "f",
    status: "active",
    date: "12/5/2023",
    email: "vsalome@test.com",
  },
  {
    id: "8",
    image:
      "https://media.istockphoto.com/id/1201144328/photo/smiling-black-man-in-suit-posing-on-studio-background.jpg?b=1&s=612x612&w=0&k=20&c=ybH24-eZo01LmM6NvB2oMYkwmTn-8DSqbF_y3zZRGSU=",
    name: "Ngolo Sabol",
    studentId: "p23y5t",
    referralCode: "e5te45",
    gender: "m",
    status: "pending",
    date: "16/8/2023",
    email: "nsabol@test.com",
  },
  {
    id: "9",
    image:
      "https://media.istockphoto.com/id/1201144328/photo/smiling-black-man-in-suit-posing-on-studio-background.jpg?b=1&s=612x612&w=0&k=20&c=ybH24-eZo01LmM6NvB2oMYkwmTn-8DSqbF_y3zZRGSU=",
    name: "Tawa Kolawale",
    studentId: "ty703e",
    referralCode: "p89y53",
    gender: "f",
    status: "active",
    date: "13/2/2023",
    email: "tkolawale@test.com",
  },
  {
    id: "10",
    image:
      "https://media.istockphoto.com/id/1201144328/photo/smiling-black-man-in-suit-posing-on-studio-background.jpg?b=1&s=612x612&w=0&k=20&c=ybH24-eZo01LmM6NvB2oMYkwmTn-8DSqbF_y3zZRGSU=",
    name: "Dare Olawale",
    studentId: "xt45tu",
    referralCode: "o90det",
    gender: "m",
    status: "pending",
    date: "27/4/2023",
    email: "dolawale@test.com",
  },
];
